<a href="https://colab.research.google.com/github/yaswanth-tech/da/blob/main/da_practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    'name':['Ravi','Priya','Arun','Sneha','Kiran','Anjali','Vikram','Menna'],
    'age':[22,24,21,25,23,26,20,27],
    'city':["hyderabad","chennai","bangalore","hyderabad","mumbai","chennai","bangalore","hyderabad"],
    'salary':[30000,40000,28000,50000,35000,45000,25000,55000]
}

df = pd.DataFrame(data)
print(df)
print("____________________")
print(df["name"])
print("____________________")
print(df[["name","salary"]])
print("____________________")
print(df[df["age"]>23])
print("____________________")
print(df[df["salary"]>40000])
print("____________________")
print(df[df["city"]=="chennai"])
print("____________________")
print(df[(df["age"] > 22) & (df["salary"] > 35000)])
print("____________________")
print(df[(df["city"] == "mumbai") | (df["city"] == "bangalore")])
print("____________________")
print(df[df["salary"] > 30000][["name", "salary"]])
print("____________________")
print(df.loc[1:3]) #we can use iloc[1:4]
print("____________________")
print(df.iloc[:4][["name", "age"]])  #we acan also use loc[:3]
print("____________________")
print(df.iloc[[0,3,6]])
print("____________________")
print(df.loc[2:5])
print("____________________")
df = df.rename(columns={
    "name": "Employee_Name",
    "age": "Employee_Age",
    "city": "Location",
    "salary": "Monthly_Salary"
})
print(df)
print("____________________")
print(df.loc[
    (df["Employee_Age"] >= 22) & (df["Employee_Age"] <= 26),
    ["Employee_Name", "Location", "Monthly_Salary"]
])

     name  age       city  salary
0    Ravi   22  hyderabad   30000
1   Priya   24    chennai   40000
2    Arun   21  bangalore   28000
3   Sneha   25  hyderabad   50000
4   Kiran   23     mumbai   35000
5  Anjali   26    chennai   45000
6  Vikram   20  bangalore   25000
7   Menna   27  hyderabad   55000
____________________
0      Ravi
1     Priya
2      Arun
3     Sneha
4     Kiran
5    Anjali
6    Vikram
7     Menna
Name: name, dtype: object
____________________
     name  salary
0    Ravi   30000
1   Priya   40000
2    Arun   28000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
6  Vikram   25000
7   Menna   55000
____________________
     name  age       city  salary
1   Priya   24    chennai   40000
3   Sneha   25  hyderabad   50000
5  Anjali   26    chennai   45000
7   Menna   27  hyderabad   55000
____________________
     name  age       city  salary
3   Sneha   25  hyderabad   50000
5  Anjali   26    chennai   45000
7   Menna   27  hyderabad   55000
____________________

In [ ]:
import pandas as pd

data = {
    "VisitID": [501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 510, 511],
    "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran", "Anjali", "Ravi", "Meena", "Arun", "Priya", "Priya", "Kiran"],
    "Department": ["Cardiology", "Neurology", "Orthopedic", "General", "Dental", "Cardiology", "Neurology", "General", "Dental", "Cardiology", "Cardiology", "Dental"],
    "BillAmount": [5000, 7500, 4500, 2000, 1500, 6000, 7000, 2500, 1800, 6000, 6000, 1500]
}

df = pd.DataFrame(data)

print(df[df.duplicated()])
print("_________________")
print(df.duplicated().sum())
print("_________________")
print(df[df.duplicated(keep=False)])
print("_________________")
print(df[df.duplicated(keep=False)]["BillAmount"].sum())
print("_________________")
print(df[df["VisitID"].duplicated(keep=False)])
print("_________________")
print(df[df["Patient"].duplicated(keep=False)])
print("_________________")
print(df.drop_duplicates())
print("_________________")
print(df.drop_duplicates(subset=["VisitID"]))
print("_________________")
print(df.drop_duplicates(subset=["Patient", "Department"]))
print("_________________")
df_cleaned = df.drop_duplicates(subset=["VisitID"])
print(df_cleaned)

    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
_________________
1
_________________
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
_________________
12000
_________________
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
_________________
    VisitID Patient  Department  BillAmount
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
_________________
    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5   

In [ ]:
df["Patient"] = df["Patient"].str.strip()
print(df)

print("_________________")

df["Patient"] = df["Patient"].str.lower()
print(df)

print("_________________")

df["Patient"] = df["Patient"].str.title()
print(df)

print("_________________")

df["Department"] = df["Department"].str.lower()
print(df)

print("_________________")

df["Department"] = df["Department"].str.title()
print(df)

print("_________________")

print(df[df["Department"].str.strip().str.lower() == "cardiology"])

print("_________________")

print(df["Department"].unique())
df["Department"] = df["Department"].str.strip().str.lower()
print(df["Department"].unique())

print("_________________")

df["Patient"] = df["Patient"].str.strip().str.title()
df["Department"] = df["Department"].str.strip().str.title()
print(df)

print("_________________")

print(df[df["Patient"].duplicated(keep=False)])

print("_________________")

df["Department"] = df["Department"].str.strip().str.title()


    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
_________________
    VisitID Patient  Department  BillAmount
0       501   rahul  Cardiology        5000
1       502   anita   Neurology        7500
2       503  suresh  Orthopedic        4500
3       504   priya     General        2000
4       505   kiran      Dental        1500
5       506  anjali  Cardiology        6000
6       507    ravi   Neurology        7000
7       508   meena     General        2500
8       509   

In [ ]:




















































































































































































































































































df = pd.read_excel(
    "/content/Sample - Superstore.csv.xlsx",
    sheet_name = "Sample - Superstore"
)
print(df)
print("____________________")
print(df.shape)
print("____________________")
print(df.head(10))
print("____________________")
print(df.tail(10))
print("____________________")
print(df[['Category','Sales']])
print("____________________")
print(df[df["Sales"] > 500])
print("____________________")
print(df[df["Profit"] > 100])
print("____________________")
print(df[df["Region"] == "West"])
print("____________________")
print(df[(df["Quantity"] > 5) & (df["Sales"] > 500)])
print("____________________")
print(df[(df["Region"] == "East") & (df["Region"] == "West")])
print("____________________")
print(df.iloc[10:20])
print("____________________")
print(df.loc[:9, ["Customer Name", "Category", "Sales", "Profit"]])
print("____________________")
print(df.iloc[[0, 5, 10, 15, 20]])
print("____________________")
print(df.loc[20:30])

df = df.rename(columns={
    "Sales": "Sales_Amount",
    "Profit": "Profit_Amount",
    "Quantity": "Quantity_Sold",
    "Category": "Product_Category"
})

print(df)

FileNotFoundError: [Errno 2] No such file or directory: '/content/Sample - Superstore.csv.xlsx'

In [ ]:
import pandas as pd

data = {
    "VisitID": [501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 510, 511],
    "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran", "Anjali",
                "Ravi", "Meena", "Arun", "Priya", "Priya", "Kiran"],
    "Department": ["Cardiology", "Neurology", "Orthopedic", "General",
                   "Dental", "Cardiology", "Neurology", "General",
                   "Dental", "Cardiology", "Cardiology", "Dental"],
    "BillAmount": [5000, 7500, 4500, 2000, 1500, 6000, 7000, 2500,
                   1800, 6000, 6000, 1500]
}

df = pd.DataFrame(data)
print(df)
print("_________________")
print(df[df.duplicated()])
print("_________________")
print(df.duplicated().sum())
print("_________________")
print(df[df.duplicated(keep = False)])
print("_________________")
print(df[df.duplicated()]['BillAmount'].sum())
print("_________________")
print(df[df["VisitID"].duplicated(keep=False)])
print("_________________")
print(df[df["Patient"].duplicated(keep=False)])
print("_________________")
print(df.drop_duplicates())
print("_________________")
print(df.drop_duplicates(subset=["VisitID"]))        #dropping duplicates of specific column
print("_________________")
print(df.drop_duplicates(subset=["Patient", "Department"]))
print("_________________")
print(df.drop_duplicates(subset=["VisitID"],keep="first"))
print("_________________")
print(df[df["Patient"]==df["Patient"].str.lower()])

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
_________________
    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
_________________
1
_________________
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
_________________
6000
_________________
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Ca

In [ ]:
df["Patient"] = df["Patient"].str.strip()
print(df)

print("_________________")

df["Patient"] = df["Patient"].str.lower()
print(df)

print("_________________")

df["Patient"] = df["Patient"].str.title()
print(df)

print("_________________")

df["Department"] = df["Department"].str.lower()
print(df)

print("_________________")

df["Department"] = df["Department"].str.title()
print(df)

print("_________________")

print(df[df["Department"].str.strip().str.lower() == "cardiology"])

print("_________________")

print(df["Department"].unique())
df["Department"] = df["Department"].str.strip().str.lower()
print(df["Department"].unique())

print("_________________")

df["Patient"] = df["Patient"].str.strip().str.title()
df["Department"] = df["Department"].str.strip().str.title()
print(df)

print("_________________")

print(df[df["Patient"].duplicated(keep=False)])

print("_________________")

df["Department"] = df["Department"].str.strip().str.title()
print(df["Department"].value_counts())

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
_________________
    VisitID Patient  Department  BillAmount
0       501   rahul  Cardiology        5000
1       502   anita   Neurology        7500
2       503  suresh  Orthopedic        4500
3       504   priya     General        2000
4       505   kiran      Dental        1500
5       506  anjali  Cardiology        6000
6       507    ravi   Neurology        7000
7       508   meena     General        2500
8       509   

In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range(start="2025-01-01",periods=60,
    freq="D")
sales = np.random.randint(
    2000,
    10000,
    size=60
)
df = pd.DataFrame({
    "Date": dates,
    "Sales": sales
})

print(df)

Date = pd.date_range(
    start="2026-01-01",
    periods = 60,
    freq = 'MS'
)
print(Date)

Date = pd.date_range(
    start="2026-01-01",
    periods = 365,
    freq = 'd'
)
print(Date)

Date = pd.date_range(
    start="2026-01-01",
    periods = 24,
    freq = 'MS'
)
print(Date)
Date = pd.date_range(
    start="2026-01-01",
    periods = 30,
    freq = 'h'
)
print(Date)
Date = pd.date_range(
    start="2020-01-01",
    periods = 60,
    freq = 'Y'
)
print(Date)

print(df.groupby(df["Date"].dt.month)["Sales"].sum())

         Date  Sales
0  2025-01-01   3808
1  2025-01-02   5114
2  2025-01-03   7684
3  2025-01-04   8240
4  2025-01-05   3420
5  2025-01-06   9829
6  2025-01-07   6162
7  2025-01-08   7128
8  2025-01-09   2062
9  2025-01-10   9431
10 2025-01-11   5469
11 2025-01-12   3951
12 2025-01-13   8310
13 2025-01-14   4693
14 2025-01-15   2818
15 2025-01-16   3284
16 2025-01-17   5630
17 2025-01-18   9378
18 2025-01-19   3945
19 2025-01-20   3811
20 2025-01-21   2386
21 2025-01-22   6729
22 2025-01-23   4550
23 2025-01-24   4816
24 2025-01-25   5297
25 2025-01-26   4343
26 2025-01-27   7056
27 2025-01-28   7096
28 2025-01-29   5280
29 2025-01-30   8110
30 2025-01-31   2504
31 2025-02-01   2155
32 2025-02-02   4309
33 2025-02-03   8535
34 2025-02-04   8902
35 2025-02-05   6600
36 2025-02-06   2390
37 2025-02-07   6006
38 2025-02-08   2496
39 2025-02-09   3164
40 2025-02-10   8686
41 2025-02-11   9190
42 2025-02-12   9529
43 2025-02-13   8965
44 2025-02-14   9456
45 2025-02-15   9436
46 2025-02-16

/tmp/ipykernel_1625/142285129.py:43: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  Date = pd.date_range(


In [ ]:
#Day-10
import pandas as pd

data = {

    "OrderID": [

        1001, 1002, 1003, 1004, 1005,

        1006, 1007, 1008, 1009, 1010,

        1011, 1012, 1013, 1014, 1015

    ],


    "OrderDateTime": [

        "2024-01-05 09:15:20",

        "2024-02-10 14:30:45",

        "2024-03-15 18:20:10",

        "2024-04-20 11:45:30",

        "2024-05-25 20:10:55",

        "2024-06-12 08:35:15",

        "2024-07-18 16:25:40",

        "2024-08-22 19:50:25",

        "2024-09-05 10:20:35",

        "2024-10-14 13:40:50",

        "2024-11-20 17:15:10",

        "2024-12-25 21:30:45",

        "2025-01-10 09:45:20",

        "2025-02-15 15:10:35",

        "2025-03-20 18:55:50"

    ],


    "Product": [

        "Laptop", "Mobile", "Tablet", "Headphones", "Keyboard",

        "Mouse", "Monitor", "Laptop", "Mobile", "Tablet",

        "Headphones", "Laptop", "Keyboard", "Monitor", "Mobile"

    ],


    "Sales": [

        55000, 25000, 30000, 5000, 3500,

        1500, 18000, 60000, 27000, 32000,

        6500, 58000, 4000, 20000, 29000

    ]

}


df = pd.DataFrame(data)


print(df)
# 1
df["OrderDateTime"] = pd.to_datetime(df["OrderDateTime"])
print(df)

# 2
df["Year"] = df["OrderDateTime"].dt.year
print(df)

# 3
df["Month"] = df["OrderDateTime"].dt.month
print(df)

# 4
df["Day"] = df["OrderDateTime"].dt.day
print(df)

# 5
df["Hour"] = df["OrderDateTime"].dt.hour
df["Minute"] = df["OrderDateTime"].dt.minute
df["Second"] = df["OrderDateTime"].dt.second
print(df)

# 6
print(df[df["Year"] == 2024])

# 7
print(df[df["Month"].isin([1, 2])])

# 8
print(df[df["Hour"].between(17, 21)])

# 9
print(df[df["Day"] == 15])

# 10
print(df.loc[df["Sales"].idxmax()])

# 11
print(df.loc[df["Sales"].idxmin()])

# 12
print(df.groupby("Year")["Sales"].sum())

# 13
monthly_sales = df.groupby("Month")["Sales"].sum()
print(monthly_sales)
print(monthly_sales.idxmax())


    OrderID        OrderDateTime     Product  Sales
0      1001  2024-01-05 09:15:20      Laptop  55000
1      1002  2024-02-10 14:30:45      Mobile  25000
2      1003  2024-03-15 18:20:10      Tablet  30000
3      1004  2024-04-20 11:45:30  Headphones   5000
4      1005  2024-05-25 20:10:55    Keyboard   3500
5      1006  2024-06-12 08:35:15       Mouse   1500
6      1007  2024-07-18 16:25:40     Monitor  18000
7      1008  2024-08-22 19:50:25      Laptop  60000
8      1009  2024-09-05 10:20:35      Mobile  27000
9      1010  2024-10-14 13:40:50      Tablet  32000
10     1011  2024-11-20 17:15:10  Headphones   6500
11     1012  2024-12-25 21:30:45      Laptop  58000
12     1013  2025-01-10 09:45:20    Keyboard   4000
13     1014  2025-02-15 15:10:35     Monitor  20000
14     1015  2025-03-20 18:55:50      Mobile  29000


In [ ]:
#Day-11
import numpy as np

one = np.arange(10,50,5)
print(one)
print("________________________")
two = np.arange(2, 30, 2)
print(two)
print("________________________")
three = np.arange(1001, 1020)
print(three)
print("________________________")
four = np.arange(50, 1, -1)
print(four)
print("________________________")
roll_numbers = np.array([101, 102, 103, 104, 105, 106, 107, 108])
print(roll_numbers)
print(roll_numbers.shape)
print(roll_numbers.ndim)

roll_numbers = np.arange(101,109).reshape(2,4)
print(roll_numbers)
print(roll_numbers.shape)
print(roll_numbers.ndim)

roll_numbers = np.arange(101,109).reshape(2,1,4)
print(roll_numbers)
print(roll_numbers.shape)
print(roll_numbers.ndim)
print("________________________")
six = np.full(10, 7)
print(six)
print(six.shape)
print(six.ndim)
one = np.full((2,5),7)
print(one)
print(one.shape)
print(one.ndim)
two = np.full((2,5,1),7)
print(two)
print(two.shape)
print(two.ndim)
print("________________________")
seven = np.zeros((2,3))
print(seven)
print("________________________")
eight = np.ones((2,3,4))
print(eight)
print("________________________")



[10 15 20 25 30 35 40 45]
________________________
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
________________________
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019]
________________________
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
________________________
[101 102 103 104 105 106 107 108]
(8,)
1
[[101 102 103 104]
 [105 106 107 108]]
(2, 4)
2
[[[101 102 103 104]]

 [[105 106 107 108]]]
(2, 1, 4)
3
________________________
[7 7 7 7 7 7 7 7 7 7]
(10,)
1
[[7 7 7 7 7]
 [7 7 7 7 7]]
(2, 5)
2
[[[7]
  [7]
  [7]
  [7]
  [7]]

 [[7]
  [7]
  [7]
  [7]
  [7]]]
(2, 5, 1)
3
________________________
[[0. 0. 0.]
 [0. 0. 0.]]
________________________
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#Day-12
import numpy as np
roll_numbers = np.array([101, 102, 103, 104, 105, 106, 107, 108])
np.random.shuffle(roll_numbers)
print(roll_numbers)
print("______________")
employees = np.array(['Ravi','Priya','Arun','Sneha','Kiran'])
np.random.shuffle(employees)
print(employees)
print("______________")
numbers = np.array([10,20,30,40,50])
result = np.random.permutation(numbers)
print("Original: ", numbers)
print("Permutation: ", result)
print("______________")
roll_numbers = np.arange(1,25).reshape(4,6)
print(roll_numbers)
print("______________")
roll_numbers = np.arange(1,21).reshape(4,5)
print(roll_numbers)
print(roll_numbers.shape)


[107 102 105 108 101 103 104 106]
______________
['Priya' 'Arun' 'Sneha' 'Kiran' 'Ravi']
______________
Original:  [10 20 30 40 50]
Permutation:  [20 50 10 30 40]
______________
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
______________
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [ ]:
one = np.array([10,20,30,40,50])
print(one)
print(one.dtype)
print(one.ndim)
print(one.shape)
print("______________")
two = np.zeros(5)
print(two)
print(two.shape)
two = np.zeros((3,4))
print(two)
print(two.shape)
two = np.zeros((2,3,4))
print(two)
print(two.shape)
print("______________")
three = np.ones(5)
print(three)
print(three.ndim)
three = np.ones((2,3))
print(three)
print(three.ndim)
three = np.ones((2,2,3))
print(three)
print(three.ndim)
print("______________")
four = np.full((4,5),1000)
print(four)
print(four.shape)
print(four.ndim)
print(four.dtype)
print("______________")
i = np.eye(5)
print(i)
print("______________")

[10 20 30 40 50]
int64
1
(5,)
______________
[0. 0. 0. 0. 0.]
(5,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
______________
[1. 1. 1. 1. 1.]
1
[[1. 1. 1.]
 [1. 1. 1.]]
2
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
3
______________
[[1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]]
(4, 5)
2
int64
______________
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#day 13
import numpy as np

one = np.linspace(0,100,10)
print(one)
print("_____________________")
two = np.linspace(1, 50, 15)
print(two)
print("_____________________")
arr = np.array([10,20,30,40,50,60,70])
print(arr[0])
print(arr[-1])
print(arr[3])
print(arr[-2])
print("_____________________")
arr = np.array([10,20,30,40,50,60,70,80])
print(arr[:4])
print(arr[2:6])
print(arr[-3:])
print(arr[::2])
for i in range(0,len(arr)-1,2):
  print(arr[i], end = " ")

print(arr[0:7:2])
print("_____________________")
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1,1])
print(arr[0,2])
print(arr[2,0])
print(arr[1])
print(arr[2])
print(arr[0:2])
print(arr[0:3,1:3])
print(arr[0:2,0:2])
print(arr[1:3])

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
_____________________
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
_____________________
10
70
40
60
_____________________
[10 20 30 40]
[30 40 50 60]
[60 70 80]
[10 30 50 70]
10 30 50 70 [10 30 50 70]
_____________________
50
30
70
[40 50 60]
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[10 20]
 [40 50]]
[[40 50 60]
 [70 80 90]]
