<a href="https://colab.research.google.com/github/yaswanth-tech/da/blob/main/da_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#day 1 11-08
def isPrime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
print("pandas imported")

pandas imported


In [ ]:
#creating series
import pandas as pd

data = [1,2,3,4]

s = pd.Series(data)

print(s)


0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
data = [1,2,3,4,5]
i = ['a','b','c','d','e']
s=pd.Series(data, index = i)
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
#crearing series from dictionary
dict = pd.Series({'yash':25,'raj':7,'yaswanth':1275})
print(dict)

yash          25
raj            7
yaswanth    1275
dtype: int64


In [ ]:
#accessing elements
print(s[:2])
print(s[0:2])
print(s[1:])
print(s[:2])

a    1
b    2
dtype: int64
a    1
b    2
dtype: int64
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
dtype: int64


In [ ]:
#position based index
print(s[2])
print(s[4])
print(s[0])

3
5
1


/tmp/ipykernel_3594/4029817636.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])
/tmp/ipykernel_3594/4029817636.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[4])
/tmp/ipykernel_3594/4029817636.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [ ]:
data = [1,2,3,4,5]
i = ['a','b','c','d','e']
s=pd.Series(data, index = i)
print(s)
#updating
s['a'] = 7
print(s)
s['e'] = 77
print(s)
#inserting new data(directly, concat)
s['m'] = 777
print(s)
#remove(drop method)
s = s.drop('c')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    7
b    2
c    3
d    4
e    5
dtype: int64
a     7
b     2
c     3
d     4
e    77
dtype: int64
a      7
b      2
c      3
d      4
e     77
m    777
dtype: int64
a      7
b      2
d      4
e     77
m    777
dtype: int64


In [ ]:
Student_ID = [101,102,103,104,105]
Marks = [78,85,92,67,88]
ma = pd.Series(Marks, index = Student_ID)
print(ma)
print(ma[103])
ma[104] = 75
print(ma)
ma = ma.drop(102)
print(ma)
ma[106] = 90
print(ma)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64


In [ ]:
Employee_ID = [1001 , 1002, 1003, 1004, 1005]
Salary = [35000, 42000, 38000, 50000, 45000]
sa = pd.Series(Salary, index = Employee_ID)
print(sa)
sa[1003]=40000
print(sa)
sa = sa.drop(1002)
print(sa)
sa[1006] = 55000
print(sa)
print(sa[:3])

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64
1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
1006    55000
dtype: int64
1001    35000
1003    40000
1004    50000
dtype: int64


In [ ]:
Product_Id = ['p101', 'p102', 'p103', 'p104', 'p105']
price = [500, 750, 1200, 900, 1500]
pr = pd.Series(price, index = Product_Id)
print(pr)
print(pr['p103'])
pr['p102'] = 800
print(pr)
pr = pr.drop('p104')
print(pr)
pr['p106'] = 2000
print(pr)

p101     500
p102     750
p103    1200
p104     900
p105    1500
dtype: int64
1200
p101     500
p102     800
p103    1200
p104     900
p105    1500
dtype: int64
p101     500
p102     800
p103    1200
p105    1500
dtype: int64
p101     500
p102     800
p103    1200
p105    1500
p106    2000
dtype: int64


In [ ]:
Week = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
temp = [31, 32, 34, 33,35,36, 34]
tp = pd.Series(temp, index = Week)
print(tp)
print(tp[:3])
tp['thursday'] = 32
print(tp)
tp = tp.drop('saturday')
print(tp)
tp['monday_next'] = 30
print(tp)

monday       31
tuesday      32
wednesday    34
thursday     33
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
sunday       34
dtype: int64
monday         31
tuesday        32
wednesday      34
thursday       32
friday         35
sunday         34
monday_next    30
dtype: int64


In [ ]:
#day-2 12-08
#view
s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)
print(s.head(3))  #takes from top
print(s.tail(2))  #takes from bottom
print(len(s))     #length
print(s.shape)    #rows and columns
print(s.index)    #all indexs
print(s.values)   #all values


monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
monday       7700
tuesday      7000
wednesday      77
dtype: int64
thursday      7
friday      777
dtype: int64
5
(5,)
Index(['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], dtype='object')
[7700 7000   77    7  777]


In [ ]:
#selecting and filtering
s['monday']               #specific index
s[['monday','wednesday']] #multiple index, nested list
s > 6000                  #filtering using a condition, gives boolen condition, true or false
s[s>6000]                 #filtering, gives only the values satisfying the condition


,0
monday,7700
tuesday,7000


In [ ]:
'''cleaning data
1)missing values-Nan-not a number
'''
s = pd.Series([77,7000,None,777,None])
print(s)
print(s.isna())       # returns the boolean value, returns true if nan, return false if value
print(s.isna().sum()) # count of missing values
print(s.fillna(0))    # fill the value u want to replace
print(s.dropna())     # drop the missing values

#manipulating
s=s.replace(5000, 5500)
print(s)

0      77.0
1    7000.0
2       NaN
3     777.0
4       NaN
dtype: float64
0    False
1    False
2     True
3    False
4     True
dtype: bool
2
0      77.0
1    7000.0
2       0.0
3     777.0
4       0.0
dtype: float64
0      77.0
1    7000.0
3     777.0
dtype: float64
0      77.0
1    7000.0
2       NaN
3     777.0
4       NaN
dtype: float64


In [ ]:
# creating DataFrame with list

import pandas as pd

data = [
    ['yaswanth', 21, 77000],
    ['rajana', 27, 7000],
    ['yashraj', 77, 700]
]

df = pd.DataFrame(data)

print(df)

          0   1      2
0  yaswanth  21  77000
1    rajana  27   7000
2   yashraj  77    700


In [ ]:
# creating Dataframe with tuple

import pandas as pd

data = [
    ('yaswanth', 21, 77000),
    ('rajana', 27, 7000),
    ('yashraj', 77, 700)
]

df = pd.DataFrame(data)

print(df)


          0   1      2
0  yaswanth  21  77000
1    rajana  27   7000
2   yashraj  77    700


In [ ]:
#creating dataframe using set
import pandas as pd

my_set = (7, 77, 777, 7777)

df_from_set = pd.DataFrame(
    list(my_set),
    columns = ['values']
)

print(df_from_set)

   values
0       7
1      77
2     777
3    7777


In [ ]:
# creating dataframe using dictionary
import pandas as pd

data = {
    'Name': ['yash', 'yaswanth', 'yashraj'],
    'age': [21, 7, 77],
    'city': ['vizag', 'ranchi', 'london']
}

df = pd.DataFrame(data)

print(df)

       Name  age    city
0      yash   21   vizag
1  yaswanth    7  ranchi
2   yashraj   77  london


In [ ]:
#converting series into dataframe
s = pd.Series(
    [7,77,777],
    name='Numbers'
)

s2 = pd.Series(
    [1,2,3],
    name='num'
)

s3 = pd.Series(
    [4,5,6],
    name='num2'
)

df = pd.DataFrame({
    'Numbers': s,
    'num': s2,
    'num2': s3
})

print(df)

   Numbers  num  num2
0        7    1     4
1       77    2     5
2      777    3     6


In [ ]:
#dataframe for 5 students with three subject marks
import pandas as pd

data = [
    ['Yaswanth', 85, 78, 90],
    ['Rahul', 75, 82, 88],
    ['Priya', 92, 89, 95],
    ['Arjun', 68, 74, 80],
    ['Sneha', 88, 91, 86]
]

df = pd.DataFrame(data, columns=['Name', 'Python', 'Maths', 'English'])

print(df)

       Name  Python  Maths  English
0  Yaswanth      85     78       90
1     Rahul      75     82       88
2     Priya      92     89       95
3     Arjun      68     74       80
4     Sneha      88     91       86


In [ ]:
#dataframe for sales, profit and loss
import pandas as pd

data = [
    ('Monday', 10000, 2000, 500),
    ('Tuesday', 12000, 2500, 400),
    ('Wednesday', 9000, 1800, 700),
    ('Thursday', 15000, 3000, 300),
    ('Friday', 11000, 2200, 600),
    ('Saturday', 18000, 4000, 200),
    ('Sunday', 14000, 2800, 500)
]

df = pd.DataFrame(data, columns=['Day', 'Sales', 'Profit', 'Loss'])

print(df)

         Day  Sales  Profit  Loss
0     Monday  10000    2000   500
1    Tuesday  12000    2500   400
2  Wednesday   9000    1800   700
3   Thursday  15000    3000   300
4     Friday  11000    2200   600
5   Saturday  18000    4000   200
6     Sunday  14000    2800   500


In [ ]:
#dataframe using dictionary
import pandas as pd

data = {
    'Name': ['Yaswanth', 'Rahul', 'Priya', 'Arjun', 'Sneha'],
    'Age': [21, 22, 20, 21, 22],
    'City': ['Vizag', 'Hyderabad', 'Vijayawada', 'Chennai', 'Bangalore']
}

df = pd.DataFrame(data)

print(df)

       Name  Age        City
0  Yaswanth   21       Vizag
1     Rahul   22   Hyderabad
2     Priya   20  Vijayawada
3     Arjun   21     Chennai
4     Sneha   22   Bangalore


In [ ]:
#day-3, 17-08
#loc
import pandas as pd

s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)

print(s.iloc[0]) #passing integer within range - iloc
print(s.iloc[0:3])
print(s.loc['monday']) #passing only user defined index - loc


monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
7700
monday       7700
tuesday      7000
wednesday      77
dtype: int64
7700


In [ ]:
import pandas as pd
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.iloc[0:2]) #it will include only starting value
print(df.loc[73])
df.loc[71:74] # it will include the starting and ending values also

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
name      nandan
age          NaN
city       delhi
salary    7777.0
Name: 73, dtype: object


,name,age,city,salary
71,yaswanth,21.0,vizag,77700.0
72,lakshman,22.0,hyderabad,7700.0
73,nandan,NaN,delhi,7777.0
74,varun,23.0,None,777.0


In [ ]:
#aggregation
s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)
print(s.min())
print(s.max())
print(s.count())
print(s.mean())
print(s.median())
print(s.std())  #standard deviation
print(s.sum())

monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
7
7700
5
3112.2
777.0
3888.1474637672886
15561


In [ ]:
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.min)
print(df.max)
print(df.count)
print(df.mean)
print(df.median)
print(df.std)

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
<bound method DataFrame.min of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.max of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.count of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75    

In [ ]:
#concat(add) multiple series
s1 = pd.Series([7,77,777])
s2 = pd.Series([1,11,111])

result = pd.concat([s1,s2], ignore_index=True) #ignore_index= True, we will reaarange the index while combining series
print(result)

0      7
1     77
2    777
3      1
4     11
5    111
dtype: int64


In [ ]:
sales = [25000, 30000, 35000, 40000, None, 45000, 50000, None, 10000, 15000 ]
i = ['01-aug','02-aug','03-aug','04-aug','05-aug','06-aug','07-aug','08-aug','09-aug','10-aug']
s = pd.Series(sales, index = i)
print(s)
print(s.head(5))
print(s.tail(3))
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
print(s[s > 35000])
s['03-aug'] = 34000
print(s)
s= s.drop('04-aug')
print(s)
s['11-aug'] = 50000
print(s)
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())

01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug        NaN
dtype: float64
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    False
02-aug    False
03-aug    False
04-aug    False
05-aug     True
06-aug    False
07-aug    False
08-aug     True
09-aug    False
10-aug    False
dtype: bool
2
01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug    31250.0
06-aug    45000.0
07-aug    50000.0
08-aug    31250.0
09-aug    10000.0
10-aug    15000.0
dtype: float64
04-aug    40000.0
06-aug    45000.0
07-aug    50000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    34000.0
04-aug    40000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float6

In [ ]:
r = [120000, 130000, None, 140000, 150000, None, 160000, 170000, 180000, 190000]
i = ['january','feburary','march','april','may','june','july','august','september','october']

s = pd.Series(r, index = i)
print(s)
print(s.head(5))
print(s.tail(3))
print(s.loc[['january','march','may']])
print(s[s>170000])
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
s['april'] = 155000
print(s)
s = s.drop('feburary')
print(s)
s['november'] = 240000
print(s)
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())

january      120000.0
feburary     130000.0
march             NaN
april        140000.0
may          150000.0
june              NaN
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january     120000.0
feburary    130000.0
march            NaN
april       140000.0
may         150000.0
dtype: float64
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january    120000.0
march           NaN
may        150000.0
dtype: float64
september    180000.0
october      190000.0
dtype: float64
january      False
feburary     False
march         True
april        False
may          False
june          True
july         False
august       False
september    False
october      False
dtype: bool
2
january      120000.0
feburary     130000.0
march        155000.0
april        140000.0
may          150000.0
june         155000.0
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype:

In [ ]:
#day-4 19-08
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name = 'numbers'
)
s2 = pd.Series([9,8,7,6])
s3 = pd.Series([11,12,13,14])

df = s.to_frame()        #for one series into dataframe
d = {
    "num1":s,
    "num2":s2,
    "num3":s3
}
df = pd.DataFrame(d)     #for multiple series into dataframe we use dictonary
print(df)
#renaming multiple columns
df.rename(
    columns = {
        'num1' : 'numbers1',
        'num2' : 'numbers2'
    },
    inplace=True
)
print(df)

#renaming single column
s = pd.Series(
    [1,2,3,4],
    name = 'numbers'
)
df = s.to_frame()
print(df)
df.columns = ['digits']
print(df)



   num1  num2  num3
0     1     9    11
1     2     8    12
2     3     7    13
3     4     6    14
   numbers1  numbers2  num3
0         1         9    11
1         2         8    12
2         3         7    13
3         4         6    14
   numbers
0        1
1        2
2        3
3        4
   digits
0       1
1       2
2       3
3       4


In [ ]:
#viewing in dataframe
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.count())
print(df.index)
print(df.values)
print(df.info())     #gives physical or structural information
print(df.describe()) #gives mahematical or statistical information

#selecting in dataframe
print(df['city'])            #for one column
print(df[['name','age']])    #for multiple columns
names = df['name']
print(names)
print(df.iloc[0])            #gives the particular row using index
print(df.iloc[0:3])          #gives multiple rows but not the end value
print(df.loc[71])            #gives particular row based on index values user-defined
print(df.loc[71:73])         #gives multiple rows including the end value


        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
      name   age       city  salary
73  nandan   NaN      delhi  7777.0
74   varun  23.0       None   777.0
75    sami  24.0  bengaluru     NaN
(5, 4)
name      5
age       4
city      4
salary    4
dtype: int64
Index([71, 72, 73, 74, 75], dtype='int64')
[['yaswanth' 21.0 'vizag' 77700.0]
 ['lakshman' 22.0 'hyderabad' 7700.0]
 ['nandan' nan 'delhi' 7777.0]
 ['varun' 23.0 None 777.0]
 ['sami' 24.0 'bengaluru' nan]]
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 71 to 75
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     4 non-null

In [ ]:
#filtering in df
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,25,None,23,24],
    'city':['vizag','hyderabad','bombay',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print("-------------------------")
print(df[df['age']>21])  #df[df] gives values of particular condition, wheres as df will give boolean values
print("-------------------------")
print(df[df['salary']>40000])
print("-------------------------")
print(df[df['city']=='hyderabad'])
print("-------------------------")
print(df[(df['age'] > 22) & (df['city'] == 'hyderabad')])
print("-------------------------")
print(df[(df['city']=='bombay') | (df['salary'] > 25000)])
print("-------------------------")
print(df.isna())       # returns the boolean value, returns true if nan, return false if value
print("-------------------------")
print(df.isna().sum()) # count of missing values
print("-------------------------")
print(df.fillna(0))    # fill the value u want to replace
print("-------------------------")
print(df.dropna())     # drop the missing values
print("-------------------------")
print(df.dropna(axis=1))  #removing columns missing values
print("-------------------------")
print(df.dropna(axis=0))
print("-------------------------")
print(df.dropna(how='all'))
print("-------------------------")
print(df.dropna(inplace=True))
print("-------------------------")
print(df.fillna(0))
print("-------------------------")
b = df.fillna({              #filling different columns with different values
    'age': 0,
    'city': 'Unknown'
})
print(b)
print("-------------------------")
df['age'] = df['age'].fillna(df['age'].mean())  #fill numerical missing values with mean


        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
73    nandan   NaN     bombay   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
74     varun  23.0       None   777.0
75      sami  24.0  bengaluru     NaN
-------------------------
        name   age   city   salary
71  yaswanth  21.0  vizag  77700.0
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
-------------------------
        name   age    city   salary
71  yaswanth  21.0   vizag  77700.0
73    nandan   NaN  bombay   7777.0
-------------------------
     name    age   city  salary
71  False  False  False   False
72  False  False  False   False
73  False   True  False   False


In [ ]:
#day-5 20-08
print(df.isna())       # returns the boolean value, returns true if nan, return false if value
print("-------------------------")
print(df.isna().sum()) # count of missing values
print("-------------------------")
print(df.fillna(0))    # fill the value u want to replace
print("-------------------------")
print(df.dropna())     # drop the missing values
print("-------------------------")
print(df.dropna(axis=1))  #removing columns missing values
print("-------------------------")
print(df.dropna(axis=0))   #removing rows
print("-------------------------")
print(df.dropna(how='all'))
print("-------------------------")
print(df.dropna(inplace=True))
print("-------------------------")
print(df.fillna(0))
print("-------------------------")
b = df.fillna({              #filling different columns with different values
    'age': 0,
    'city': 'Unknown'
},inplace=True)
print(b)
print("-------------------------")
df['age'] == df['age'].fillna(df['age'].mean())
print(df)  #fill numerical missing values with mean


     name    age   city  salary
71  False  False  False   False
72  False  False  False   False
-------------------------
name      0
age       0
city      0
salary    0
dtype: int64
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
None
-------------------------
        name   age       city   salary
71  ya

In [ ]:
emp_details = {
    'emp_id' :[71,72,73,74,71],
    'city' : ['hyderabad','chennai','bangalore',None,'hyderabad'],
    'experience' : [None, 4, 3, 5, 2],
    'age':[25,30, None, 35,25]

}
df=pd.DataFrame(emp_details)
print(df)
print("-------------------------")
print(df.isna())
print("-------------------------")
print(df.dropna())
print("-------------------------")
print(df.isna().sum())
print("-------------------------")
b = df.fillna({           #experience =0, city = unknown
    'experience': 0,
    'city': 'Unknown'
},inplace = True)
print(b)
df['age'] == df['age'].fillna(df['age'].median(), inplace = True)   #age=median
print(df)
print("-------------------------")
df.rename(columns={"emp_id":'employee_id'},inplace=True)   #replace emp_id as employee_id
#create new column as salary for all employees --- manipulating
df['salary'] = [77000, None, 7777, 77770, 777]
print(df)
print("-------------------------")
df['age'] = df['age'] + 1        #age + 1
print(df)
print("-------------------------")
df['bonus'] = df['salary'] / 10  #10% bonus to salary
print(df)
print("-------------------------")
df.drop('bonus', axis =1 , inplace = True)  #drop bonus column
print(df)
print("-------------------------")
#df.drop(columns=['age', 'salary'],inplace=True)-drop multiple columns
df.loc[len(df)] = [77, 'vizag', 7, 17, 77]
print(df)
print("-------------------------")
df.drop(2,axis = 0, inplace = True)   #dropping a specific row
print(df)
print("-------------------------")

   emp_id       city  experience   age
0      71  hyderabad         NaN  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0   NaN
3      74       None         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------------------
   emp_id   city  experience    age
0   False  False        True  False
1   False  False       False  False
2   False  False       False   True
3   False   True       False  False
4   False  False       False  False
-------------------------
   emp_id       city  experience   age
1      72    chennai         4.0  30.0
4      71  hyderabad         2.0  25.0
-------------------------
emp_id        0
city          1
experience    1
age           1
dtype: int64
-------------------------
None
   emp_id       city  experience   age
0      71  hyderabad         0.0  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0  27.5
3      74    Unknown         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------

In [ ]:
#groupby
emp_details = {
    'emp_id' :[71,72,73,74,71],
    'city' : ['hyderabad','chennai','bangalore',None,'hyderabad'],
    'experience' : [None, 4, 3, 5, 2],
    'age':[25,30, None, 35,25]

}
df=pd.DataFrame(emp_details)
print(df)
print("-------------------------")
print(df.groupby('city')['age'].mean())
print("-------------------------")
print(df.groupby('city')['age'].median())
print("-------------------------")
print(df.groupby('city')['age'].min())
print("-------------------------")
print(df.groupby('city')['age'].max())
print("-------------------------")
print(df.groupby('city')['age'].count())
print("-------------------------")
print(df.groupby('city')['age'].agg([    #aggregations on single column
    'mean',
    'max',
    'min',
    'sum'
]))
print(df.groupby('city').agg({            #multiple aggregations on multiple columns
    'age':['mean','max'],
    'experience':['sum','count']
}))


   emp_id       city  experience   age
0      71  hyderabad         NaN  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0   NaN
3      74       None         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore    0
chennai      1
hyderabad    2
Name: age, dtype: int64
-------------------------
           mean   max   min   sum
city                             
bangalore   NaN   NaN   NaN   0.0
chennai    30.0  30.0  30.0  30.0
hyderabad  25.0  25.0  25.0  50.0
            age       expe

In [ ]:
#day-6 21-06
#merging and joining
df1 = pd.DataFrame({
    'id':[7,8,9],
    'name':['M','S','D']
})

df2 = pd.DataFrame({
    'id':[7,1,2],
    'name':[77,777,7777]
})

merged = pd.merge(
    df1,
    df2,
    on = 'id',
    how = 'outer'    #it joins the both tables rows
)
print(merged)
print("-------------------------")
merged = pd.merge(
    df1,
    df2,
    on = 'id',
    how = 'inner'    #it joins only common rows
)
print(merged)
print("-------------------------")
merged = pd.merge(
    df1,
    df2,
    on = 'id',
    how = 'left'     #it joins the left table rows and common rows
)
print(merged)
print("-------------------------")
merged = pd.merge(
    df1,
    df2,
    on = 'id',
    how = 'right'    #it joind right table rows and common rows
)
print(merged)
print("-------------------------")

#concat

combined = pd.concat(
    [df1,df2],
    axis = 0,            #adds rows vertically
    ignore_index=True    #re arranges
)
print(combined)
print("-------------------------")
combined = pd.concat(
    [df1,df2],
    axis = 1,            #adds columns hortizonatally
)
print(combined)

   id name_x  name_y
0   1    NaN   777.0
1   2    NaN  7777.0
2   7      M    77.0
3   8      S     NaN
4   9      D     NaN
-------------------------
   id name_x  name_y
0   7      M      77
-------------------------
   id name_x  name_y
0   7      M    77.0
1   8      S     NaN
2   9      D     NaN
-------------------------
   id name_x  name_y
0   7      M      77
1   1    NaN     777
2   2    NaN    7777
-------------------------
   id  name
0   7     M
1   8     S
2   9     D
3   7    77
4   1   777
5   2  7777
-------------------------
   id  name  id  name
0   7     M   7    77
1   8     S   1   777
2   9     D   2  7777


In [ ]:
#read csv file
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df)
print("-------------------------")
print(df.head(7))
print("-------------------------")
print(df.tail(7))
print("-------------------------")
print(df.count())
print("-------------------------")
print(df.min())
print("-------------------------")
print(df.max())
print("-------------------------")
print(df.info())
print("-------------------------")
print(df.describe())
print("-------------------------")
print(df.shape)
print("-------------------------")


      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value

In [ ]:
#day 07 22-08
#reading excel file
df = pd.read_excel(
    "/content/Sample - Superstore.csv.xlsx",
    sheet_name = "Sample - Superstore"
)
print(df)
print("-------------------------")
print(df.head(7))
print("-------------------------")
print(df.tail(7))
print("-------------------------")
print(df.count())
print("-------------------------")
print(df.min())
print("-------------------------")
print(df.max())
print("-------------------------")
print(df.info())
print("-------------------------")
print(df.describe())
print("-------------------------")
print(df.shape)
print("-------------------------")


      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson 

In [ ]:
#duplicates
import pandas as pd
data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)
print("____________________")
print(df.duplicated())       #finds duplicates, and if duplicate returns true
print("____________________")
print(df.duplicated().sum()) #total number of duplicate rows
print("____________________")
duplicate = df[df.duplicated()]
print(duplicate)             #display duplicate rows
print("____________________")
duplicate = df[df.duplicated(keep=False)]
print(duplicate)             #display actual and duplicate rows
print("____________________")
duplicate_rows = df[df.duplicated()]
total = duplicate_rows["Salary"].sum()  #sum of salary of duplicate row
print(total)
print("____________________")
duplicate_rows = df[df.duplicated(keep = False)]
total = duplicate_rows["Salary"].sum()        #sum of salary of actual and duplicate row
print(total)
print("____________________")
print(df['City'].duplicated())                #identify and return true for only selected column
print("____________________")
print(df[df['EmpID'].duplicated()])           #identify and return the duplicated entire row
print("____________________")
print(df[df["EmpID"].duplicated(keep=False)]) #return entire actual and duplicate rows/using primary key easy to find
print("____________________")
df = df.drop_duplicates()                    #removes duplicates, keep = "first"-last duplicate is removed, keep = "last" - first row will be removed
print(df)
print("_________________")
df["City"]=df["City"].str.title()
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000
____________________
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool
____________________
1
____________________
    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000
____________________
    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000
____________________
45000
____________________
90000
____________________
0     False
1      True
2     False
3     False
4     False
5     False

In [ ]:
#Dataset 1 – Customer Transactions
#This dataset represents customer purchase transactions.

import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df_sales = pd.DataFrame(data)

print(df_sales)
print("____________________")
print(df_sales[df_sales.duplicated()])
print("____________________")
print(df_sales.duplicated().sum())
print("____________________")
print(df_sales[df_sales.duplicated(keep=False)])
print("____________________")
duplicate_rows = df_sales[df_sales.duplicated()]
total = duplicate_rows["Amount"].sum()  #sum of salary of duplicate row
print(total)
print("____________________")
print(df_sales[df_sales['TransactionID'].duplicated()])
print("____________________")
print(df_sales[df_sales['Customer'].duplicated()])
print("____________________")
df_sales = df_sales.drop_duplicates()
print(df_sales)
print("____________________")
print(df_sales.drop_duplicates(subset=["TransactionID"],keep = "first"))        #dropping duplicates of specific column
print("_________________")
print(df_sales.drop_duplicates(subset=["Customer","Product"],keep= "first"))
print("_________________")


    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
____________________
    TransactionID Customer     Product  Amount
10           1010    Sneha  Headphones    5000
____________________
1
____________________
    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
____________________
5000
____________________
    TransactionID Customer     Product  Am

In [ ]:
#day 8 24-08
#handling manuplation
print(df_sales[df_sales["Customer"] == df_sales["Customer"].str.title()])      #tittle:first latter of each captil
print("----------------------------------------------")
print(df_sales[df_sales["Customer"] == df_sales["Customer"].str.lower()])
print("----------------------------------------------")
print(df_sales[df_sales["Customer"] == df_sales["Customer"].str.strip()])
print("----------------------------------------------")
print(df_sales[df_sales["Product"] == df_sales["Product"].str.lower()])
print("----------------------------------------------")
print(df_sales[df_sales["Product"] == df_sales["Product"].str.title()])
print("----------------------------------------------")
df_sales["Product"], df_sales["Customer"] == df_sales["Product"].str.strip(),df_sales["Customer"].str.title()
print(df_sales)
print("----------------------------------------------")
print(df_sales[df_sales["Product"]=="Laptop"])
print("----------------------------------------------")
print(df_sales[df_sales["Customer"]=="sneha"])
print("----------------------------------------------")
df_sales["Product"], df_sales["Customer"] == df_sales["Product"].str.strip().str.title(),df_sales["Customer"].str.strip().str.title()
print(df_sales)

Empty DataFrame
Columns: [TransactionID, Customer, Product, Amount]
Index: []
----------------------------------------------
    TransactionID Customer     Product  Amount
0            1001     ravi      Laptop   55000
1            1002    priya      Mobile   25000
2            1003     arun      Tablet   30000
3            1004    sneha  Headphones    5000
4            1005    kiran       Mouse    1500
5            1006   anjali    Keyboard    2500
6            1007   vikram     Monitor   18000
7            1008    meena      Laptop   55000
8            1009    rahul      Mobile   22000
9            1010    sneha  Headphones    5000
11           1011    kiran       Mouse    1500
----------------------------------------------
    TransactionID Customer     Product  Amount
0            1001     ravi      Laptop   55000
1            1002    priya      Mobile   25000
2            1003     arun      Tablet   30000
3            1004    sneha  Headphones    5000
4            1005    kiran   

In [ ]:
#day 9 25-08
#time series
import pandas as pd

data = {
    "Date" :[
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05",
        "2025-01-06",
        "2025-01-07",
        "2025-01-08",
        "2025-01-09",
        "2025-01-10"
    ],
    "sales":[5000,6500,4200,7000,5500,4000,3000,6000,7700,770]
}
df = pd.DataFrame(data)
print(df)
print("______________________")
print(df.dtypes)
df["Date"] = pd.to_datetime(df["Date"])    #chnaging column to datetime
print(df.dtypes)
print("______________________")
Date = pd.date_range(                 #getting data of specific column using start and end
    start = "2025-01-01",
    end = "2025-01-07"
)
print(Date)
print("______________________")
Date = pd.date_range(                 #getting data of specific column using start and period
    start = "2025-01-01",
    periods = 7
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 18,
    freq = 'D'                     #freq='d' is for dates
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 12,
    freq = 'ME'                       #freq='ME'- is for month ending dates, 'MS' - is for month starting dates
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 12,
    freq = "Y"                       #freq='Y' is for year
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 12,
    freq = 'h'                       #'h'-hourly
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 12,
    freq = 'min'                     #'min'-minutes
)
print(Date)
print("______________________")
Date = pd.date_range(
    start="2026-01-01",
    periods = 12,
    freq = 's'                        #s-seconds
)
print(Date)

         Date  sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500
5  2025-01-06   4000
6  2025-01-07   3000
7  2025-01-08   6000
8  2025-01-09   7700
9  2025-01-10    770
Date     object
sales     int64
dtype: object
Date     datetime64[ns]
sales             int64
dtype: object
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01

/tmp/ipykernel_1363/1043888580.py:47: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  Date = pd.date_range(


In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range(start="2025-01-01",periods=60,
    freq="D")
sales = np.random.randint(
    2000,
    10000,
    size=60
)
df = pd.DataFrame({
    "Date": dates,
    "Sales": sales
})

print(df)
print("______________________")
df["Date"] = pd.to_datetime(df["Date"])
print(df)
#year
print("______________________")
df["Date"].dt.year
print(df[df["Date"].dt.year == 2026])
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].sum())
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].max())
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].min())
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].mean())
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].count())
print("______________________")
print(df.groupby(df["Date"].dt.year)["Sales"].median())
print("______________________")


         Date  Sales
0  2025-01-01   8320
1  2025-01-02   8659
2  2025-01-03   6171
3  2025-01-04   4558
4  2025-01-05   2691
5  2025-01-06   5023
6  2025-01-07   8277
7  2025-01-08   2229
8  2025-01-09   8141
9  2025-01-10   6415
10 2025-01-11   7896
11 2025-01-12   7315
12 2025-01-13   9056
13 2025-01-14   7241
14 2025-01-15   9850
15 2025-01-16   2323
16 2025-01-17   8332
17 2025-01-18   4513
18 2025-01-19   3313
19 2025-01-20   8989
20 2025-01-21   8892
21 2025-01-22   7400
22 2025-01-23   8593
23 2025-01-24   5222
24 2025-01-25   6509
25 2025-01-26   2057
26 2025-01-27   6964
27 2025-01-28   9508
28 2025-01-29   6967
29 2025-01-30   4379
30 2025-01-31   3869
31 2025-02-01   9073
32 2025-02-02   3474
33 2025-02-03   8648
34 2025-02-04   5655
35 2025-02-05   7720
36 2025-02-06   6473
37 2025-02-07   2090
38 2025-02-08   8878
39 2025-02-09   7009
40 2025-02-10   7787
41 2025-02-11   3248
42 2025-02-12   2846
43 2025-02-13   2380
44 2025-02-14   2042
45 2025-02-15   6924
46 2025-02-16

In [ ]:
#month
df["Date"].dt.month
print(df["Date"].dt.month_name)
print("______________________")
print(df[df["Date"].dt.month == 2])
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].sum())
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].max())
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].min())
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].mean())
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].count())
print("______________________")
print(df.groupby(df["Date"].dt.month)["Sales"].median())
print("______________________")

<bound method PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>.f of <pandas.core.indexes.accessors.DatetimeProperties object at 0x79e8e240ee40>>
______________________
         Date  Sales
31 2025-02-01   9073
32 2025-02-02   3474
33 2025-02-03   8648
34 2025-02-04   5655
35 2025-02-05   7720
36 2025-02-06   6473
37 2025-02-07   2090
38 2025-02-08   8878
39 2025-02-09   7009
40 2025-02-10   7787
41 2025-02-11   3248
42 2025-02-12   2846
43 2025-02-13   2380
44 2025-02-14   2042
45 2025-02-15   6924
46 2025-02-16   6224
47 2025-02-17   5895
48 2025-02-18   7091
49 2025-02-19   3282
50 2025-02-20   9027
51 2025-02-21   3720
52 2025-02-22   8190
53 2025-02-23   6908
54 2025-02-24   6800
55 2025-02-25   9083
56 2025-02-26   5393
57 2025-02-27   2079
58 2025-02-28   5449
______________________
Date
1    199672
2    163388
3      3447
Name: Sales, dtype: int64
______________________
Date
1    9850
2    9083
3    3447
Name: Sales, dtype: int64
________________

In [ ]:
#day
df["Date"].dt.day
df["Date"].dt.day_name()
print(df[df["Date"].dt.day == 15])
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].sum())
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].max())
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].min())
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].mean())
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].median())
print("______________________")
print(df.groupby(df["Date"].dt.day)["Sales"].count())


         Date  Sales
14 2025-01-15   9850
45 2025-02-15   6924
______________________
Date
1     20840
2     12133
3     14819
4     10213
5     10411
6     11496
7     10367
8     11107
9     15150
10    14202
11    11144
12    10161
13    11436
14     9283
15    16774
16     8547
17    14227
18    11604
19     6595
20    18016
21    12612
22    15590
23    15501
24    12022
25    15592
26     7450
27     9043
28    14957
29     6967
30     4379
31     3869
Name: Sales, dtype: int64
______________________
Date
1     9073
2     8659
3     8648
4     5655
5     7720
6     6473
7     8277
8     8878
9     8141
10    7787
11    7896
12    7315
13    9056
14    7241
15    9850
16    6224
17    8332
18    7091
19    3313
20    9027
21    8892
22    8190
23    8593
24    6800
25    9083
26    5393
27    6964
28    9508
29    6967
30    4379
31    3869
Name: Sales, dtype: int64
______________________
Date
1     3447
2     3474
3     6171
4     4558
5     2691
6     5023
7     2090
8     2229


In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range(start="2025-01-01",periods=60,
    freq="D")
sales = np.random.randint(
    2000,
    10000,
    size=60
)
df = pd.DataFrame({
    "Date": dates,
    "Sales": sales
})

print(df)

Date = pd.date_range(
    start="2026-01-01",
    periods = 60,
    freq = 'MS'
)
print(Date)

Date = pd.date_range(
    start="2026-01-01",
    periods = 365,
    freq = 'd'
)
print(Date)

Date = pd.date_range(
    start="2026-01-01",
    periods = 24,
    freq = 'MS'
)
print(Date)
Date = pd.date_range(
    start="2026-01-01",
    periods = 30,
    freq = 'h'
)
print(Date)
Date = pd.date_range(
    start="2020-01-01",
    periods = 60,
    freq = 'Y'
)
print(Date)

print(df.groupby(df["Date"].dt.month)["Sales"].sum())

         Date  Sales
0  2025-01-01   5090
1  2025-01-02   2042
2  2025-01-03   3314
3  2025-01-04   4979
4  2025-01-05   6099
5  2025-01-06   8075
6  2025-01-07   8684
7  2025-01-08   5978
8  2025-01-09   9547
9  2025-01-10   9358
10 2025-01-11   9037
11 2025-01-12   9666
12 2025-01-13   9341
13 2025-01-14   6388
14 2025-01-15   8397
15 2025-01-16   6397
16 2025-01-17   6231
17 2025-01-18   6025
18 2025-01-19   8949
19 2025-01-20   3423
20 2025-01-21   3860
21 2025-01-22   3947
22 2025-01-23   9235
23 2025-01-24   9763
24 2025-01-25   6776
25 2025-01-26   3017
26 2025-01-27   2694
27 2025-01-28   5865
28 2025-01-29   3027
29 2025-01-30   2307
30 2025-01-31   4629
31 2025-02-01   4278
32 2025-02-02   4356
33 2025-02-03   9550
34 2025-02-04   2198
35 2025-02-05   5821
36 2025-02-06   7551
37 2025-02-07   6996
38 2025-02-08   5070
39 2025-02-09   6306
40 2025-02-10   4374
41 2025-02-11   4320
42 2025-02-12   6899
43 2025-02-13   3191
44 2025-02-14   4513
45 2025-02-15   5515
46 2025-02-16

In [ ]:
#day 10 26-08
#apply
import pandas as pd
data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)
df["Salary"] = df["Salary"].apply(lambda x: x * 1.10)
print(df)


    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000
    EmpID    Name       City   Salary
0     101    Ravi  Hyderabad  33000.0
1     102   PRIYA  Hyderabad  44000.0
2     103    Arun    CHENNAI  38500.0
3     104   sneha    Chennai  49500.0
4     105   Kiran  Bangalore  35200.0
5     106  ANJALI  BANGALORE  55000.0
6     107  Vikram     Mumbai  41800.0
7     108   meena     mumbai  46200.0
8     109   RAHUL      Delhi  39600.0
9     110   Sneha  Hyderabad  49500.0
10    110   Sneha  Hyderabad  49500.0


In [ ]:
#map:
City_codes = {
    'Hyderabad': "HYD",
    'Chennai':"CHE",
    'Bangalore':"BAN",
    "Mumbai":"MUM",
    "Delhi":"DEL"
}
df["City_codes"] = df["City"].map(City_codes)
print(df)

    EmpID    Name       City   Salary City_codes
0     101    Ravi  Hyderabad  33000.0        HYD
1     102   PRIYA  Hyderabad  44000.0        HYD
2     103    Arun    CHENNAI  38500.0        NaN
3     104   sneha    Chennai  49500.0        CHE
4     105   Kiran  Bangalore  35200.0        BAN
5     106  ANJALI  BANGALORE  55000.0        NaN
6     107  Vikram     Mumbai  41800.0        MUM
7     108   meena     mumbai  46200.0        NaN
8     109   RAHUL      Delhi  39600.0        DEL
9     110   Sneha  Hyderabad  49500.0        HYD
10    110   Sneha  Hyderabad  49500.0        HYD


In [ ]:
#day 11 27-08
#numpy
!pip install numpy
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
import numpy as np

numbers = np.array([7,8,9,10])
print(numbers)
print(numbers.ndim)     #checking numbers ofdimension of array
print(numbers.shape)

num = np.array([[1,2,3],[5,7,9]])
print(num)
print(num.ndim)
print(num.shape)

num1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(num1)
print(num1.ndim)
print(num1.shape)



[ 7  8  9 10]
1
(4,)
[[1 2 3]
 [5 7 9]]
2
(2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [ ]:
#arange -- sequence of numbers

arr = np.arange(1, 8)         #range
print(arr)
print("________________________")
arr1 = np.arange(0, 100, 7)   #step
print(arr1)
print("________________________")
arr2 = np.zeros(7)           #returns only 0's
print(arr2)
print("________________________")
arr3 = np.zeros((2,3))       #returns 0's in rows and columns(2d)
print(arr3)
print("________________________")
arr4 = np.zeros((2,2,3))     #returns 0's in height, rows and columns(3d)
print(arr4)
print("________________________")
arr5 = np.ones(7)            #returns only 1's
print(arr5)
print("________________________")
full = np.full(5, 7)        #(count, value)
print(full)
print("________________________")
full1 = np.full((2,3),7)     #2d
print(full1)
print("________________________")
full2 = np.full((2,3,4),7)   #3d
print(full2)
print("________________________")
re = np.arange(1,10)
print(re)
shape = re.reshape(3,3)     #reshape, into rows and columns and range should be multiply the rows and columns(2d)
print(shape)
print("________________________")
re = np.arange(1,13)
print(re)
shape = re.reshape(2,3,2)     #reshape, into shape, rows and columns and range should be multiply the shape, rows and columns(3d)
print(shape)
print("________________________")
res = np.arange(1,11).reshape(5,2)    #reshape with arange and reshape in one line
print(res)

[1 2 3 4 5 6 7]
________________________
[ 0  7 14 21 28 35 42 49 56 63 70 77 84 91 98]
________________________
[0. 0. 0. 0. 0. 0. 0.]
________________________
[[0. 0. 0.]
 [0. 0. 0.]]
________________________
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
________________________
[1. 1. 1. 1. 1. 1. 1.]
________________________
[7 7 7 7 7]
________________________
[[7 7 7]
 [7 7 7]]
________________________
[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
________________________
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
________________________
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
________________________
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
int = np.array([7.7, 77.7, 7.0, 7], dtype = "str")     #it convert all values to string, because string is highest priority

print(int)
print(int.dtype)

int = np.array([7.7, 77.7, 7.0, 7], dtype = "int")    #it convert into integers

print(int)
print(int.dtype)

int = np.array([7.7, 77.7, 7.0, 7], dtype = "float")  #it convert into float

print(int)
print(int.dtype)

#int = np.array([7.7, 77.7, 7.0, 7, "a"], dtype = "int") --> this will throw valueerror because string can't convert into int

names = np.array(["yash","kams","hasi","raju","raj"], dtype = "str")

print(names)
print(names.dtype)

['7.7' '77.7' '7.0' '7']
<U4
[ 7 77  7  7]
int64
[ 7.7 77.7  7.   7. ]
float64
['yash' 'kams' 'hasi' 'raju' 'raj']
<U4


In [ ]:
#day 12 28-08
import numpy as np
#identity matrix - diagonals will be one(square matrix)
i = np.eye(7)
print(i)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#numpy random package
ran = np.random.random(7)           #0-1 float numbers
print(ran)
print("______________")
ran1 = np.random.random((2,3))      #for 2d
print(ran1)
print("______________")
ran3 = np.random.random((2,3,4))    #for 3d
print(ran3)
print("______________")
ran4 = np.random.uniform(7, 77, 7)  #uniform- here(low, high, size)
print(ran4)
print("______________")
ran5 = np.random.uniform(7,77,(2,4)) #2d
print(ran5)
print("______________")
ran6 = np.random.uniform(7,77,(2,2,3))#3d
print(ran6)
print("______________")
ran7 = np.random.randn(7)            #randn- gives random values with mean = 0, standard deviation = 1
print(ran7)
print(ran7.mean())
print(ran7.std)
print("______________")
ran7 = np.random.randn(2,3)            #randn- 2d
print(ran7)
print(ran7.mean())
print(ran7.std)
print("______________")
ran7 = np.random.randn(2,2,3)            #randn-3d
print(ran7.mean())
print(ran7.std)
print("______________")
cho = np.array([7,77,777,7777])         #choice- gives the random values from the given array
result = np.random.choice(cho)          #gives multiple use (arr,number)
print(result)
print("______________")
str = ["yash","kams","hasi","raju","raj"]  #gives with string
result = np.random.choice(str,2)
print(result)
print("______________")
pro = [7,77,777]                           #choice probability, here we have, arr, size = number, p = sum should be 1
result = np.random.choice(
    pro,
    size = 4,
    p=[0.5,0.2,0.3]
)
print(result)
print("______________")
sd = np.random.uniform(7, 77)
np.random.seed(10)                        #seed - freeze the random number, so it doesn't change, it doesn't generate, seed(nummber) - number is number of times it freezes
print(sd)
print("______________")
sd1 = np.random.random(7)
np.random.seed(7)
print(sd1)
print("______________")
sd2 = np.random.randn(7)
np.random.seed(7)
print(sd2)
print("______________")
cho = np.array([7,77,777,7777])
result = np.random.choice(cho)
np.random.seed(7)
print(result)
print("______________")
cho = np.array([7,77,777,7777])        #shuffle- different orders  - changes original array
np.random.shuffle(cho)
print(cho)
print("______________")
cho = np.array([7,77,777,7777])       #permutation-orginal will be same, permutation will duplicate order
result = np.random.permutation(cho)
print("Original":cho)
print("Permutation":result)
print("______________")

[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951 0.53849587
 0.50112046]
______________
[[0.07205113 0.26843898 0.4998825 ]
 [0.67923    0.80373904 0.38094113]]
______________
[[[0.06593635 0.2881456  0.90959353 0.21338535]
  [0.45212396 0.93120602 0.02489923 0.60054892]
  [0.9501295  0.23030288 0.54848992 0.90912837]]

 [[0.13316945 0.52341258 0.75040986 0.66901324]
  [0.46775286 0.20484909 0.49076589 0.37238469]
  [0.47740115 0.36589039 0.83791799 0.76864751]]]
______________
[28.9796274  47.08377329 26.32343338 38.69900528 31.70848562 53.01796239
 32.92457581]
______________
[[39.13650845 57.35268858 35.90942804 70.44962884]
 [19.63161334 58.8783211  36.56618306 36.85175009]]
______________
[[[51.4065908  43.60343407 36.04201849]
  [ 7.09988164 13.45836421 56.65760756]]

 [[43.70419177 55.73123245 73.88278261]
  [54.80396981 10.71900835 28.61968794]]]
______________
[-1.43496347  0.50162412 -0.09477545  1.19308592 -0.36881847 -1.90636988
 -0.09961063]
-0.3156896928319394
<bui

In [ ]:
#day-13 29-08
#linspace-- its the difference equally b/w numbers
import numpy as np
lin = np.linspace(0, 7, 7)
print(lin)
print("_____________________")
#shape- attribute for giving rows and columns
arr = np.array([10,20,30,40])
print(arr.shape)
print("_____________________")
#ravel - compress multi into single(1-d)

ra = np.array([[1,2,3,4],[5,6,7,8]]) #2d to 1d
result = ra.ravel()
print(result)

ra1 = np.arange(1,10).reshape(3,3,1)   #3D TO 1D
result = ra1.ravel()
print(result)
print("_____________________")
#transponse
tra = np.arange(1,11).reshape(2,5)
print(tra)
r = tra.T
print(r)
print("_____________________")

#Data type conversion
dt = np.array([10,20,30,40])
print(dt)
print(dt.dtype)
data = dt.astype(float)
print(data)
print(data.dtype)
print("_____________________")
arr = np.array([10,20,30,40,50])    #1d
print(arr[-3:-1])     #last 2rd, 3rd
print(arr[-2:])       #last 2
print(arr[0:2])       #first 2

arr1 = np.arange(1,11).reshape(2,5)   #2d
print(arr1)
print(arr1[0,3])
print(arr1[0:1])        #slicing rows
print(arr1[0:2,0:4])     #slicing in 2d for rows and columns
print("_____________________")
#modification
mod = np.array([10,20,30,40,50])   #1d
mod[2] = 70
print(mod)

mod1 = np.arange(1,11).reshape(2,5) #2d
mod1[0] = 7
print(mod1)

mod[1:3] = 7   #multiple elements in 1d
print(mod)
print("_____________________")
#insert
ns = np.insert(mod, 4, 77)
print(ns)

ns = np.insert(mod, 3, [7,77])   #inserting multiple values
print(ns)
print("_____________________")
#delete
de = np.array([10,20,30,40,50])
dele = np.delete(de, 4)
print(dele)

dele = np.delete(de, [1,2])   #deleting multiple values
print(dele)



[0.         1.16666667 2.33333333 3.5        4.66666667 5.83333333
 7.        ]
_____________________
(4,)
_____________________
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
_____________________
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
_____________________
[10 20 30 40]
int64
[10. 20. 30. 40.]
float64
_____________________
[30 40]
[40 50]
[10 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4
[[1 2 3 4 5]]
[[1 2 3 4]
 [6 7 8 9]]
_____________________
[10 20 70 40 50]
[[ 7  7  7  7  7]
 [ 6  7  8  9 10]]
[10  7  7 40 50]
_____________________
[10  7  7 40 77 50]
[10  7  7  7 77 40 50]
_____________________
[10 20 30 40]
[10 40 50]


In [ ]:
import numpy as np

