<a href="https://colab.research.google.com/github/yaswanth-tech/da/blob/main/numpyexam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# 1. Create a 1D NumPy array and display dimensions, shape, size and datatype

one = np.array([10, 20, 30, 40, 50])

print(one)
print("Dimensions:", one.ndim)
print("Shape:", one.shape)
print("Size:", one.size)
print("Data type:", one.dtype)

print("_____________")


# 2. Create 2D and 3D arrays

two = np.arange(1, 13).reshape(3, 4)
print(two)

three = np.arange(1, 25).reshape(2, 3, 4)
print(three)

print("_____________")


# 3. Create 1D, 2D and 3D arrays containing zeros

one_zero = np.zeros(4)
print(one_zero)

two_zero = np.zeros((2, 3))
print(two_zero)

three_zero = np.zeros((2, 3, 4))
print(three_zero)

print("_____________")


# 4. Create a 2 × 3 array containing ones

four = np.ones((2, 3))

print(four)
print("Dimensions:", four.ndim)
print("Shape:", four.shape)

print("_____________")


# 5. Create a 3 × 4 array of 7s and a 4 × 4 identity matrix

five = np.full((3, 4), 7)
print(five)

identity = np.eye(4)
print(identity)

[10 20 30 40 50]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64
_____________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
_____________
[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
_____________
[[1. 1. 1.]
 [1. 1. 1.]]
Dimensions: 2
Shape: (2, 3)
_____________
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
import numpy as np


# 6. Generate five random decimal values between 0 and 1
# and a 2 × 3 array of random decimal values

six = np.random.random(5)
print(six)

six_2 = np.random.random((2, 3))
print(six_2)

print("_____________")


# 7. Generate a 3 × 3 array of random values between 10 and 50

seven = np.random.uniform(10, 50, (3, 3))
print(seven)

print("_____________")


# 8. Generate a 2 × 4 array following standard normal distribution

eight = np.random.randn(2, 4)
print(eight)

print("_____________")


# 9. Randomly select 3 colors

colors = ["Red", "Blue", "Green", "Yellow", "Black"]

nine = np.random.choice(colors, 3, replace=False)
print(nine)

print("_____________")


# 10. Generate five random numbers with a fixed seed
# and generate them again

np.random.seed(7)
first = np.random.random(5)
print("First set:", first)

np.random.seed(7)
second = np.random.random(5)
print("Second set:", second)

print("Both are identical:", np.array_equal(first, second))

[0.53849587 0.50112046 0.07205113 0.26843898 0.4998825 ]
[[0.67923    0.80373904 0.38094113]
 [0.06593635 0.2881456  0.90959353]]
_____________
[[18.53541414 28.08495847 47.24824079]
 [10.9959691  34.0219567  48.00518002]
 [19.21211516 31.93959677 46.365135  ]]
_____________
[[ 0.07066062 -1.10711737  0.79418452  1.17666305]
 [-1.43532596 -0.15681862 -2.32884309 -0.16851266]]
_____________
['Black' 'Yellow' 'Red']
_____________
First set: [0.07630829 0.77991879 0.43840923 0.72346518 0.97798951]
Second set: [0.07630829 0.77991879 0.43840923 0.72346518 0.97798951]
Both are identical: True


In [6]:
import numpy as np


# 11. Create numbers from 5 to 50 with a step of 5

eleven = np.arange(5, 51, 5)
print(eleven)

print("_____________")


# 12. Randomly change original array and create a reordered copy

arr = np.array([10, 20, 30, 40, 50, 60])

# Changes the original array
np.random.shuffle(arr)
print("Changed original:", arr)

# Creates a randomly reordered copy
new_arr = np.random.permutation(arr)
print("Reordered copy:", new_arr)

print("_____________")


# 13. Generate 6 equally spaced values between 0 and 100

thirteen = np.linspace(0, 100, 6)
print(thirteen)

print("_____________")


# 14. Arrange array into 3 × 4 matrix and convert back to 1D

arr = np.array([1, 2, 3, 4, 5, 6,
                7, 8, 9, 10, 11, 12])

matrix = arr.reshape(3, 4)
print("3 × 4 Matrix:")
print(matrix)

one_d = matrix.ravel()
print("1D Array:")
print(one_d)

print("_____________")


# 15. Change rows into columns and columns into rows
# Also create a 3D array

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:")
print(arr)

print("Transpose:")
print(arr.T)

arr3d = arr.reshape(2, 1, 3)
print("3D Array:")
print(arr3d)

[ 5 10 15 20 25 30 35 40 45 50]
_____________
Changed original: [50 60 40 30 20 10]
Reordered copy: [60 40 30 10 20 50]
_____________
[  0.  20.  40.  60.  80. 100.]
_____________
3 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
_____________
Original:
[[1 2 3]
 [4 5 6]]
Transpose:
[[1 4]
 [2 5]
 [3 6]]
3D Array:
[[[1 2 3]]

 [[4 5 6]]]


In [7]:
import numpy as np


# 16. Display datatype and convert values to floating-point

arr = np.array([10, 20, 30, 40, 50])

print("Original data type:", arr.dtype)

arr = arr.astype(float)

print("Float array:", arr)
print("New data type:", arr.dtype)

print("_____________")


# 17. Retrieve 50, last row, first two columns and change 80 to 800

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Retrieve 50
print("50:", arr[1, 1])

# Retrieve last row
print("Last row:", arr[-1])

# Retrieve first two columns
print("First two columns:")
print(arr[:, :2])

# Change 80 to 800
arr[2, 1] = 800

print("After changing 80 to 800:")
print(arr)

print("_____________")


# 18. Insert 25, remove 40 and perform mathematical analysis

arr = np.array([10, 20, 30, 40, 50])

# Add 25 between 20 and 30
arr = np.insert(arr, 2, 25)
print("After insertion:", arr)

# Remove 40
arr = np.delete(arr, 3)
print("After deletion:", arr)

print("Total:", np.sum(arr))
print("Smallest:", np.min(arr))
print("Largest:", np.max(arr))
print("Average:", np.mean(arr))

print("_____________")


# 19. Statistical analysis

marks = np.array([45, 56, 67, 72, 81, 90, 95])

print("Variance:", np.var(marks))
print("Standard deviation:", np.std(marks))
print("25th percentile:", np.percentile(marks, 25))
print("75th percentile:", np.percentile(marks, 75))
print("Position of highest mark:", np.argmax(marks))
print("Position of lowest mark:", np.argmin(marks))
print("Base-10 logarithm:", np.log10(marks))

print("_____________")


# 20. Combining arrays

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])


# Combine A and B into one continuous array
result = np.concatenate((A, B))
print("Continuous A and B:")
print(result)


# Arrange A and B one below the other
result = np.vstack((A, B))
print("A and B vertically:")
print(result)


# Arrange A and B along a newly created dimension
result = np.stack((A, B), axis=0)
print("New dimension:")
print(result)


# Combine all three arrays vertically
result = np.vstack((A, B, C))
print("All three vertically:")
print(result)


# Combine all three arrays horizontally
result = np.hstack((A, B, C))
print("All three horizontally:")
print(result)


# Divide combined 1D array into 3 equal parts
result = np.concatenate((A, B, C))

parts = np.split(result, 3)

print("Three equal parts:")
print(parts)

Original data type: int64
Float array: [10. 20. 30. 40. 50.]
New data type: float64
_____________
50: 50
Last row: [70 80 90]
First two columns:
[[10 20]
 [40 50]
 [70 80]]
After changing 80 to 800:
[[ 10  20  30]
 [ 40  50  60]
 [ 70 800  90]]
_____________
After insertion: [10 20 25 30 40 50]
After deletion: [10 20 25 40 50]
Total: 145
Smallest: 10
Largest: 50
Average: 29.0
_____________
Variance: 277.63265306122446
Standard deviation: 16.662312356369522
25th percentile: 61.5
75th percentile: 85.5
Position of highest mark: 6
Position of lowest mark: 0
Base-10 logarithm: [1.65321251 1.74818803 1.8260748  1.8573325  1.90848502 1.95424251
 1.97772361]
_____________
Continuous A and B:
[1 2 3 4 5 6]
A and B vertically:
[[1 2 3]
 [4 5 6]]
New dimension:
[[1 2 3]
 [4 5 6]]
All three vertically:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
All three horizontally:
[1 2 3 4 5 6 7 8 9]
Three equal parts:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
