<a href="https://colab.research.google.com/github/yaswanth-tech/da/blob/main/numpyexam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
one = np.array([10,20,30,40,50])
print(one)
print(one.shape)
print(one.size)
print(one.ndim)
print(one.dtype)
print("_____________")
two = np.arange(1,13).reshape(3,4)
print(two)
two = np.arange(1,25).reshape(2,3,4)
print(two)
print("_____________")
three = np.zeros(4)
print(three)
three = np.zeros((2,3))
print(three)
three = np.zeros((2,3,4))
print(three)
print("_____________")
four = np.ones((2,3))
print(four)
print(four.ndim)
print(four.shape)
print("_____________")
five = np.full((3,4),7)
print(five)
five = np.eye(4)
print(five)
print("_____________")
six = np.random.random(5)
print(six)
six = np.random.randn(2,3)
print(six)
print("_____________")
seven = np.random.uniform(10,50, (3,3))
print(seven)
print("_____________")
eight = np.random.uniform(0,40,(2,4))
print(eight)
print("_____________")
nine = np.array(["red","blue","green","yellow","black"])
n = np.random.choice(nine, 3)
print(n)
print("_____________")
ten = np.random.uniform(1,10,5)
np.random.seed(7)    #shuffle two times and compare
print(ten)
print("_____________")
eleven = np.arange(5,51,5)
print(eleven)
print("_____________")
arr = np.array([10,20,30,40,50,60])
a = np.random.permutation(arr)
print("original:",arr)
print("permutation",a)
print("_____________")
t2 = np.linspace(0,100,6)
print(t2)
print("_____________")
t3 = np.arange(1,13).reshape(3,4)
print(t3)
t = t3.ravel()
print(t)
print("_____________")
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
a = arr.T
print(a)
arr2 = np.array([[1,2,3],[4,5,6]]).reshape(2,1,3)
print(arr2)
print("_____________")
arr = np.array([10,20,30,40,50], dtype = "float")
print(arr)
print("_____________")

[10 20 30 40 50]
(5,)
5
1
int64
_____________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
_____________
[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
_____________
[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)
_____________
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
_____________
[0.67923    0.80373904 0.38094113 0.06593635 0.2881456 ]
[[-0.01496821  0.02139067  0.74878108]
 [-0.08313583  0.07072914 -0.33420021]]
_____________
[[48.00518002 19.21211516 31.93959677]
 [46.365135   15.32677783 30.93650323]
 [40.01639436 36.76052964 28.71011439]]
_____________
[[ 8.19396361 19.63063556 14.89538758 19.09604619]
 [14.63561543 33.51671977 30.74590026 12.55978709]]
_____________
['red' 'black' 'yellow']
_____________
[5.92511614 3.79188318 3.54447754 9.28894186 4

In [54]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1,1])
print(arr[2])
print(arr[0:3,1:3])
arr[2,1]= 800
print(arr)
print("_____________")
arr = np.array([10,20,30,40,50])
arr1 = np.insert(arr, 2, 25)
print(arr1)
#remove 40, total, smallest, largest value, average, variance, std, 25th percentile
arr2 = np.delete(arr, 3)
print(arr2)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print("_____________")
print(np.var(arr))
print(np.std(arr))
print(np.percentile(arr, 25))
print("_____________")
#a to b
#a to b in below
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(np.concatenate((a,b)))
result = np.stack((a,b),axis = 0)
print(result)

50
[70 80 90]
[[20 30]
 [50 60]
 [80 90]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70 800  90]]
_____________
[10 20 25 30 40 50]
[10 20 30 50]
150
10
50
30.0
_____________
200.0
14.142135623730951
20.0
_____________
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [63]:
#a and b to newly created dimension, all three vertically, hortizontally, into 1d to 3 equally
result = np.stack([[1,2,3],[4,5,6]],axis = 0)
print(result)
result = np.stack([a,b,c],axis = 1)  #hortizontal
print(result)
result = np.stack([a,b,c],axis = 0)  #vertical
print(result)

[[1 2 3]
 [4 5 6]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
